// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/19/2025, 5:52:47 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/joseong-u/WebstormProjects/hanteo_project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joseong-u/WebstormProjects/hanteo_project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joseong-u/WebstormProjects/hanteo_project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joseong-u/WebstormProjects/hanteo_project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joseong-u/WebstormProjects/hanteo_project/plugins/**/*.{js,ts,mjs}","/Users/joseong-u/WebstormProjects/hanteo_project/composables/**/*.{js,ts,mjs}","/Users/joseong-u/WebstormProjects/hanteo_project/utils/**/*.{js,ts,mjs}","/Users/joseong-u/WebstormProjects/hanteo_project/pages/index.vue","/Users/joseong-u/WebstormProjects/hanteo_project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/joseong-u/WebstormProjects/hanteo_project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/joseong-u/WebstormProjects/hanteo_project/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;
